# Generated by Django 4.2.11 on 2024-05-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custommodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custommodel',
            managers=[
            ],
        ),
    ]
