# Generated by Django 4.2.11 on 2024-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
