# Generated by Django 4.2.11 on 2024-05-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
