# Generated by Django 4.2.11 on 2024-05-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_sunjectmarks_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sunjectmarks',
            name='Total_marks',
        ),
        migrations.AddField(
            model_name='student',
            name='Total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
