# Generated by Django 4.2.11 on 2024-05-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_remove_sunjectmarks_total_marks_student_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunjectmarks',
            name='show_total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
